# Generated by Django 5.2.3 on 2025-07-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('chip', 'Chip'), ('dip', 'Dip')], max_length=4)),
            ],
        ),
    ]
